### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by santosadrian** [whyynoot/Likee-Video-Downloader#2]
python3 main.py
Enter Likee page url: https://likee.video/*********
Getting user info...
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    main()
  File "main.py", line 58, in main
    user_info = get_user_info(get_user_uid(input("Enter Likee page url: ")))
  File "main.py", line 15, in get_user_uid
    final = json.loads(final.replace(";", ''))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by whyynoot** [comment]
Hello! For me every thing works fine!

I suggest u are trying to enter the video link, but u have to enter PROFILE LINK, and programm will download ALL videos from profile.

[image](https://user-images.githubusercontent.com/63478397/127561087-f83695d1-9f6a-41e9-9d42-c2585a0e87c2.png)

Maybe sometime, i will add feauture to download only one video from profile, but now U CAN DOWNLOAD ALL VIDEOS FROM PROFILE BY A PROFILE LINK. 

Example input: https://likee.video/@_ket_fom_/ 
(dont know who is this, but i think she wont be angry for me doing this)

**Comment by santosadrian** [comment]
Sorry to telll you I eddited the url before posting with **** , I put a complete url profile, like now:
https://imgur.com/a/gplFWLC If don't misssing something. 

Don't know why don't work, everything is updated, Ubuntu kernel 5.0.0-32-generic.

Thanks

**Comment by whyynoot** [comment]
I checked the account u are trying to act with. 

I am currently getting this: 
![/@Nadia.Vilaplana6/ screenshot](https://user-images.githubusercontent.com/63478397/127683754-77b5cb20-ae69-4d9c-8709-ded11ef1c9ea.png)

I don't know why download is not starting, I suggest because the profile is maybe private or smth. Because it is showing that the user has 65 videos, but none of them are showed to me. 
![Empty VideoList](https://user-images.githubusercontent.com/63478397/127684586-90746799-4d3b-499b-9539-6d2ab98c59fe.png)


But, about your error, dont know why are u getting this. Something is wierd in Likee i suggest. 
Because this error is about getting json format from the main page. Did u edit some code trying to add auth?

**Comment by santosadrian** [comment]
likee It's very weird in fact, page acts differently sometimes show videos, sometimes not, plus the app in android that is another thing... I'm watching close likee.video

No, I did not edited nothing

Ah the url is "random", I don't want nothing from that likee profile.

**Comment by whyynoot** [comment]
Okay, can u change the 15 line
`final = json.loads(final.replace(";", ''))`
To this 
```
final = final.replace(";", '')
print(final)
final = json.loads(final)
```
And show me the output of the code u are getting this time.
